### ISSUE TITLE
站点问题 Issue

### ISSUE THREAD

**Issue by PlayMcBKuwu** [PlayMcBKuwu/chinagpt#1]
如果突然遇到站点链接无法访问等问题，请在本 Issue 下回复。

**Comment by delandwu** [comment]
推荐一个国内直接能用的ChatGPT站点，响应速度很快，支持上下文和多话题，有一些免费额度。

https://chat.uniation.net

**Comment by PlayMcBKuwu** [comment]
> 推荐一个国内直接能用的ChatGPT站点，响应速度很快，支持上下文和多话题，有一些免费额度。
> 
> https://chat.uniation.net

感谢补充

**Comment by johnsonwong666** [comment]
投稿 chat.xiami.monster

**Comment by PlayMcBKuwu** [comment]
> 投稿 chat.xiami.monster

THX

**Comment by johnsonwong666** [comment]
投稿。chat.xiamis.xyz

**Comment by johnsonwong666** [comment]
推荐站点第七条  https://chat.xiami.monster/#/chat/1002 这个已经废弃 保留后面那个发布页吧。
然后支持3.5/4.0 dalle-e/stable diffusion绘画、思维导图
希望能够补充一下，提高一点权重，感谢

**Comment by PlayMcBKuwu** [comment]
> 推荐站点第七条 https://chat.xiami.monster/#/chat/1002 这个已经废弃 保留后面那个发布页吧。 然后支持3.5/4.0 dalle-e/stable diffusion绘画、思维导图 希望能够补充一下，提高一点权重，感谢

3Q

**Comment by PlayMcBKuwu** [comment]
本 Issue 改为用户自行添加的 Issue，Templates（模板）已设置完毕。

**Comment by PlayMcBKuwu** [comment]
本 Issue 重新启用，但不准备 **「Reopen」** ，因为仍旧属于废弃情况。
